import type { Metadata } from "next";
import { Playwrite_DE_SAS, Manrope } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme/theme-provider";
import AuthGate from "@/components/auth/auth-gate";
import { Toaster } from "sonner";

const playwriteDESAS = Playwrite_DE_SAS({
  variable: "--font-playwrite-de-sas",
});

const manrope = Manrope({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${manrope.className} ${playwriteDESAS.variable} antialiased min-w-sm`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthGate>
            {children}
            <Toaster />
          </AuthGate>
        </ThemeProvider>
      </body>
    </html>
  );
}
